window.SENTENCES_AUDIO_MAP = {
  "Letter ar. Sound a. Find the word that starts with ar.": "assets/audios/sentences/frog_prompt_ar.mp3",
  "Letter ar. Sound /a/. Find the word that starts with ar.": "assets/audios/sentences/frog_prompt_ar.mp3",
  "Letter ar. Find the word that starts with ar": "assets/audios/sentences/frog_intro_ar.mp3",
  "Letter er. Sound e. Find the word that starts with er.": "assets/audios/sentences/frog_prompt_er.mp3",
  "Letter er. Sound /e/. Find the word that starts with er.": "assets/audios/sentences/frog_prompt_er.mp3",
  "Letter er. Find the word that starts with er": "assets/audios/sentences/frog_intro_er.mp3",
  "Letter ir_ur. Sound i. Find the word that starts with ir_ur.": "assets/audios/sentences/frog_prompt_ir_ur.mp3",
  "Letter ir_ur. Sound /i/. Find the word that starts with ir_ur.": "assets/audios/sentences/frog_prompt_ir_ur.mp3",
  "Letter ir_ur. Find the word that starts with ir_ur": "assets/audios/sentences/frog_intro_ir_ur.mp3",
  "What does the teacher say? The teacher says: Please stand up and sing.": "assets/audios/sentences/frog_act_4692048c.mp3",
  "The teacher says: Please stand up and sing. What does the teacher say?": "assets/audios/sentences/frog_act_4692048c.mp3",
  "Where should you sit down? Please sit down on your wooden chair.": "assets/audios/sentences/frog_act_70af5cca.mp3",
  "Please sit down on your wooden chair. Where should you sit down?": "assets/audios/sentences/frog_act_70af5cca.mp3",
  "What is the classroom rule? Be quiet when reading a story in the library.": "assets/audios/sentences/frog_act_cca855b2.mp3",
  "Be quiet when reading a story in the library. What is the classroom rule?": "assets/audios/sentences/frog_act_cca855b2.mp3",
  "What tool do you use to measure? Use your yellow ruler to measure the long line.": "assets/audios/sentences/frog_act_b2e9633c.mp3",
  "Use your yellow ruler to measure the long line. What tool do you use to measure?": "assets/audios/sentences/frog_act_b2e9633c.mp3",
  "What should you open? Open your book and look at the lesson.": "assets/audios/sentences/frog_act_5b8ba59b.mp3",
  "Open your book and look at the lesson. What should you open?": "assets/audios/sentences/frog_act_5b8ba59b.mp3"
};
